# -*- coding: utf-8 -*-
"""AV_Dashboard_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jk_kEeLQtDpkiU8wvfq6N8Ky8F_5BUD_
"""

!pip install ultralytics opencv-python-headless ipython
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/data/kitti
!wget -c https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_image_2.zip -O /content/data/kitti/kitti_images.zip
!unzip -q /content/data/kitti/kitti_images.zip -d /content/data/kitti/
!wget -c https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_label_2.zip -O /content/data/kitti/kitti_labels.zip
!unzip -q /content/data/kitti/kitti_labels.zip -d /content/data/kitti/

kitti_images_path = "/content/data/kitti/training/image_2"
kitti_labels_path = "/content/data/kitti/training/label_2"

print("KITTI images path:", kitti_images_path)
print("KITTI labels path:", kitti_labels_path)

from ultralytics import YOLO

# Load a pretrained YOLOv8 model for object detection
# You can replace this with your own trained weights later
model_det = YOLO("yolov8n.pt")  # 'n' = nano model, small and fast

# Load a YOLOv8 segmentation model for lane detection
model_seg = YOLO("yolov8n-seg.pt")  # segmentation model

import cv2
from matplotlib import pyplot as plt

# Load a sample image from KITTI
sample_img_path = kitti_images_path + "/000000.png"  # first image
img = cv2.imread(sample_img_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Run detection
results = model_det.predict(img_rgb)

# Show results
results[0].plot()  # plots the bounding boxes
plt.imshow(results[0].plot())
plt.axis('off')
plt.show()

import cv2

# Video path (update if your video has a different name)
video_path = "/content/drive/MyDrive/AV_Project/data/video/test_drive.mp4"

# Open video
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Output video
out = cv2.VideoWriter('/content/AV_Dashboard_Output.mp4',
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      fps, (frame_width, frame_height))

print("Video setup complete!")

# For tracking previous positions
prev_centers = {}

# To store trajectories for all objects
trajectories = []

import numpy as np
from PIL import Image
from IPython.display import display, clear_output
import time

# Class colors and names for visualization
class_colors = {0:(0,255,0), 1:(255,0,0), 2:(0,165,255)}
class_names = {0:'Car', 1:'Pedestrian', 2:'Cyclist'}

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Lane segmentation
    seg_results = model_seg.predict(frame, imgsz=640, conf=0.25, verbose=False)
    frame_overlay = frame.copy()
    if len(seg_results[0].masks.data) > 0:
        seg_mask = seg_results[0].masks.data[0].cpu().numpy()
        seg_mask = (seg_mask * 255).astype(np.uint8)
        seg_mask_color = cv2.applyColorMap(seg_mask, cv2.COLORMAP_JET)
        frame_overlay = cv2.addWeighted(frame, 0.7, seg_mask_color, 0.3, 0)
        cv2.putText(frame_overlay, "Lane Mask", (10,30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)

    # Object detection
    results = model_det.track(frame_overlay, tracker="bytetrack.yaml", stream=False)
    frame_vis = frame_overlay.copy()

    for det in results[0].boxes:
        obj_id = det.id
        cls_id = int(det.cls[0])
        xmin, ymin, xmax, ymax = map(int, det.xyxy[0])
        cx, cy = (xmin + xmax)//2, (ymin + ymax)//2

        # Calculate velocity
        if obj_id in prev_centers:
            dx = cx - prev_centers[obj_id][0]
            dy = cy - prev_centers[obj_id][1]
            velocity = np.sqrt(dx**2 + dy**2) * fps
        else:
            velocity = 0
        prev_centers[obj_id] = (cx, cy)

        # Trajectories
        if obj_id >= len(trajectories):
            trajectories.append([])
        trajectories[obj_id].append((cx, cy))
        for i in range(1, len(trajectories[obj_id])):
            cv2.line(frame_vis, trajectories[obj_id][i-1],
                     trajectories[obj_id][i], (255,255,0), 2)

        # Predicted next position
        if len(trajectories[obj_id]) >= 2:
            dx_pred = trajectories[obj_id][-1][0] - trajectories[obj_id][-2][0]
            dy_pred = trajectories[obj_id][-1][1] - trajectories[obj_id][-2][1]
            pred_x = int(trajectories[obj_id][-1][0] + dx_pred)
            pred_y = int(trajectories[obj_id][-1][1] + dy_pred)
            cv2.circle(frame_vis, (pred_x, pred_y), 5, (0,0,255), -1)

        # Draw bounding box and info
        color = class_colors.get(cls_id, (0,255,255))
        cv2.rectangle(frame_vis, (xmin, ymin), (xmax, ymax), color, 2)
        cv2.putText(frame_vis, f"{class_names.get(cls_id,'Unknown')} ID:{obj_id} V:{velocity:.1f}px/s",
                    (xmin, ymin-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    # Save frame to video
    out.write(frame_vis)

    # Display in Colab
    img_display = cv2.cvtColor(frame_vis, cv2.COLOR_BGR2RGB)
    display(Image.fromarray(img_display))
    clear_output(wait=True)
    time.sleep(0.03)

cap.release()
out.release()
print("Processing complete! Output saved as AV_Dashboard_Output.mp4")

